# SITE SETTINGS
# global meta settings
languages: [nl, fr]
title:
  nl: Brandsfit
  fr: Brandsfit
description:
  nl: Verruim je clubbudget
  fr: Augmentez le budget de votre club
keywords:
  nl: clubbudget
  fr: budget de club
baseurl: 
exclude: ['README.md']

# COLLECTIONS
collections:
  jobs:
    title: Jobs
    output: true
    url: jobs

# LANGUAGES
l:
  nl: Nederlands
  fr: Français

# TRANSLATIONS
t:
  nl:
    helpdesk: Bel onze helpdesk
    netherlands: Nederland
    belgium: België
    club_webshop: Club Webshop
    register_club: Registreer je club
    register_club_url: registreer-club
    call: <u>Bel ons</u> voor een afspraak of meer informatie
    appointment: <u><strong>Maak een afspraak</strong></u> met mij en scoor je gratis tenues
    karel_brandsfit: Karel van Brandsfit
    email: Email ons
  fr:
    helpdesk: Contactez notre service client
    netherlands: Les Pays-Bas
    belgium: Belgique
    club_webshop: Boutique en ligne
    register_club: Registrez votre club
    register_club_url: registrez-club
    call: <u>Appelez-nous</u> pour un rendez-vous ou plus d'informations
    appointment: <u><strong>Prenez un rendez-vous</strong></u> avec moi et recevez des tenues gratuites !
    karel_brandsfit: Karel de Brandsfit
    email: Nous envoyer un courriel

# NAVIGATION
# main top navigation
# be sure to add both languages
navi:
  nl:
    clubs:
      name: Kiezen voor Brandsfit
      url: /
    about:
      name: Over Brandsfit
      url: /over-brandsfit
    jobs:
      name: Jobs
      url: /jobs
    visibility:
      name: Visibiliteit
      url: /visibiliteit
  fr:
    clubs:
      name: Choisir pour Brandsfit
      url: /
    about:
      name: Au sujet de brandsfit
      url: /au-sujet-de-brandsfit
    jobs:
      name: Emplois
      url: /emplois
    visibility:
      name: Visibilité
      url: /visibilite

      
# BLOCKS
# render the header and footer block with right language
blocks:
  nl:
  fr:
